articles/forms.py, articles/templates/articles/detail.html, articles/urls.py, articles/views.py, templates/base.html
feat: articles comments & like function / 박혜진
=> feat: articles comments & like function / 박혜진

articles/templates/articles/detail.html, articles/views.py
fix: comment delete function / 박혜진
=> fix: comment delete function / 박혜진

articles/templates/articles/detail.html, articles/urls.py, articles/views.py, templates/base.html
fix: like function not-complete / 박혜진
=> fix: like function not-complete / 박혜진

articles/templates/articles/detail.html, articles/urls.py, articles/views.py
=> fix: like function / 박혜진

static/css/font.css, templates/base.html
=> feat: add font

RIP_pjt/urls.py, RIP_pjt/views.py, templates/base.html, templates/home.html
fix : navbar css 수정 및 home.html articles data 출력 확인/김나형
=> fix : navbar css 수정 및 home.html articles data 출력 확인/김나형

articles/templates/articles/detail.html, champions/templates/champions/index.html, champions/urls.py, champions/views.py, opgg_crawling.py, static/css/font.css
=> feat: 챔피언 앱 디테일 페이지 크롤링 / 박혜진

accounts/templates/accounts/member.html, accounts/urls.py, accounts/views.py, static/css/accounts.css, static/js/accounts.js, templates/nonavbase.html
=> feat: 프로그래스바 초안/김나형

articles/views.py, champions/templates/champions/index.html, champions/views.py, static/crawling/c_code/json_file.py, static/crawling/c_code/opgg_crawling.py, static/crawling/json/adc.json, static/crawling/json/infos.json, static/crawling/json/jungle.json, static/crawling/json/mid.json, static/crawling/json/support.json, static/crawling/json/top.json, static/css/champions_index.css
fix: 챔피언앱 랭킹 탭메뉴 구현 및 크롤링 데이터 json으로 저장/박혜진
=> fix: 챔피언앱 랭킹 탭메뉴 구현 및 크롤링 데이터 json으로 저장/박혜진

accounts/templates/accounts/login.html, static/css/accounts.css, templates/accountsBase.html
=> degign: accounts login /김나형

accounts/templates/accounts/detail.html, accounts/templates/accounts/mypage.html, accounts/templates/accounts/password.html, templates/accountsBase.html
design: accounts nav,second nav/김나형
=> design: accounts nav,second nav/김나형

static/css/base.css, templates/accountsBase.html, templates/base.html
=> design: base navbar 변경

accounts/templates/accounts/detail.html, accounts/templates/accounts/mypage.html, accounts/views.py, static/css/accountsBase.css
=> design: account detail 완료/김나형

accounts/templates/accounts/detail.html, accounts/templates/accounts/login.html, accounts/views.py, static/css/base.css, templates/accountsBase.html, templates/base.html
chore: 자잘한 링크와 반응형 정리 (nav, login)/김나형
=> chore: 자잘한 링크와 반응형 정리 (nav, login)/김나형

champions/models.py, champions/templates/champions/detail.html, champions/templates/champions/index.html, champions/urls.py, champions/views.py
fix: champions app 디테일 페이지 수정 / 박혜진
=> fix: champions app 디테일 페이지 수정 / 박혜진

accounts/templates/accounts/mypage.html, accounts/templates/accounts/password.html, accounts/templates/accounts/password_reset.html, accounts/templates/accounts/password_reset_done.html, static/css/accounts.css, static/css/accountsDetail.css, static/js/accounts.js, templates/nonavbase.html
=> feat: accounts 앱 반응형/김나형

accounts/templates/accounts/password_reset.html, accounts/templates/accounts/password_reset_complete.html, accounts/templates/accounts/password_reset_confirm.html, accounts/templates/accounts/password_reset_done.html, accounts/views.py, static/css/accounts.css
fix: 비밀번호 변경시 이메일 post 문제 view 수정 및 pw email 디자인 전체 수정/김나형
=> fix: 비밀번호 변경시 이메일 post 문제 view 수정 및 pw email 디자인 전체 수정/김나형

accounts/templates/accounts/member.html, accounts/templates/accounts/pre_delete.html, static/css/accounts.css, static/js/accounts.js, templates/accountsBase.html, templates/nonavbase.html
[chore: js 페이지 리로드 막아 놓는 코드 주석처리/김나형]
=> chore: js 페이지 리로드 막아 놓는 코드 주석처리/김나형

RIP_pjt/settings.py, requirements.txt, static/css/accounts.css, static/css/base.css, templates/accountsBase.html, templates/base.html, templates/home.html, templates/homeBase.html
chore:home design 반응형/김나형
기능 추가 필요 (검색)
articles 인기순 출력 필요
=> chore:home design 반응형/김나형

templates/accountsBase.html, templates/base.html, templates/homeBase.html
=> chore: nav 자잘한 거/김나형
